version: '3.8'

name: 'neversitup-kafka-lab'

networks:
  app-tier:
    driver: bridge

services:
  kafka:
    container_name: 'my-kafka'
    image: 'bitnami/kafka:latest'
    networks:
      - app-tier
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      
  orderapp:
    container_name: 'order-app'
    build:
      context: .
      dockerfile: Dockerfile.OrderApp
    networks:
      - app-tier
    ports:
      - '1323:1323'
    depends_on:
      - kafka

  stockapp:
    container_name: 'stock-app'
    build:
      context: .
      dockerfile: Dockerfile.StockApp
    networks:
      - app-tier
    depends_on:
      - kafka

  paymentapp:
    container_name: 'payment-app'
    build:
      context: .
      dockerfile: Dockerfile.PaymentApp
    networks:
      - app-tier
    depends_on:
      - kafka
    