FROM golang:1.21-alpine AS build

WORKDIR /app

COPY . ./
RUN go mod download

RUN CGO_ENABLED=0 go build -o /bin/app

FROM gcr.io/distroless/static-debian11

COPY --from=build /bin/app /bin
COPY /env/.env.stock /bin

EXPOSE 1323

ENTRYPOINT [ "/bin/app", "/bin/.env.stock" ]